### PR TITLE
Initial implementation of voice file output.

### LINKED ISSUE #202: Include the voice file name as a string for NPC voiced output in websocket JSON
In the websocket JSON, it would be great to output the filename of the voiced NPC line along with the text, and a flag denoting the message as a spoken line. This is useful if a websocket listener would like to do some pre-processing on audio in real time.

Note, I plan to implement this myself -- this bug is for tracking purposes. I'm going to start by changing the knownVoiceLinePtrs HashSet to a Dictionary that contains a k/v of the pointer and filename, then use that to propagate the data down to PollAddon, and then down to... I haven't gotten that far yet :)

Thanks!

### PR DESCRIPTION
**Pull request by Cidan**
Fixes #202

### CODE REVIEW

**Comment by Cidan** [comment]
This is the initial implementation, and there's pretty much nothing I like about this change. It feels like a quick hack, so I'm going to rethink this one. I'm also second-guessing it's utility, as externally, there's no good way to extract voice data, apply a DSP, then play it, without the wealth of tooling in the game client.

**Review by karashiiro — COMMENTED** [review]
Yeah, I feel a large part of the issue here is just how `SoundHandler` interacts with `Addon(Battle)TalkHandler` - it basically fakes a state change to populate the dedupe states early. I'm really not a fan of how that system works, but I haven't been able to come up with a good alternative.

Really, it should emit its own set of events which suppress `Addon(Battle)TalkHandler` events from being processed by the `Say` pipeline, but I haven't figured that out, yet. At that point, `TextEmitEvent` could be unassociated with voice lines altogether, and you could just process them without additional context as they're detected.

However, all of that does leave one remaining problem in that your WebSocket client needs to be able to extract the resulting sound file from `sqpack`, and there aren't many good libraries for that across programming languages ([Lumina](https://github.com/NotAdam/Lumina), [Ironworks](https://github.com/ackwell/ironworks), [Kobold](https://github.com/ackwell/kobold)).

At any rate, turning `SoundHandler` into an event emitter of some kind is probably the first step in cleaning this up.

**Comment by karashiiro** [comment]
> I'm also second-guessing it's utility, as externally, there's no good way to extract voice data, apply a DSP, then play it, without the wealth of tooling in the game client.

Yeah this is also a problem, since you'd presumably want to mute the in-game line for this, and that's a whole other discussion

**Comment by karashiiro** [comment]
From a UX perspective, I'd actually say that should maybe be its own plugin, unless it were to also apply to TTT's TTS.

**Comment by Cidan** [comment]
> From a UX perspective, I'd actually say that should maybe be its own plugin, unless it were to also apply to TTT's TTS.

Yeah, I came to that conclusion as well about 2 hours ago while mulling this over. It would actually be even better to just implement a DSP in C# and configure the whole thing in-game. I'll toy around with it. I'm going to close this PR as it's clear this isn't the form nor function that should be taken for this.

**Pull request closed without merging**
